[project]
name = "SuperNodes"
description = "A node pack by SuperCC."
version = "0.3.5"
license = { file = "LICENSE" } 
dependencies  = ["matplotlib"]

[project.urls]
Repository = "https://github.com/sonnybox/ComfyUI-SuperNodes"

[tool.comfy]
PublisherId = "sonnybox"
DisplayName = "ComfyUI-SuperNodes"
Icon = "https://raw.githubusercontent.com/sonnybox/ComfyUI-SuperNodes/refs/heads/main/logo.png"
