[project]
name = "comfyui-supernodes"
description = "A miscellaneous node pack of custom implementations needed for workflows released by my SuperComfy YouTube channel."
version = "0.3.0"
license = { file = "LICENSE" } 
dependencies  = ["matplotlib"]

[project.urls]
Repository = "https://github.com/sonnybox/ComfyUI-SuperNodes"

[tool.comfy]
PublisherId = "sonnybox"
DisplayName = "ComfyUI-SuperNodes"
Icon = "https://raw.githubusercontent.com/sonnybox/ComfyUI-SuperNodes/refs/heads/main/logo.png"
