import torch


def generate_feather_mask(shape, radius, device):
    """
    Generates a weight mask with a linear fade-out at the edges.
    shape: (H, W, C) or (H, W)
    radius: pixels to fade
    """
    h, w = shape[:2]
    mask = torch.ones((h, w), dtype=torch.float32, device=device)

    if radius <= 0:
        return mask

    # Clamp radius to half the size to prevent negative indices
    # This automatically handles "max amount" blending when a large radius is requested
    radius = min(radius, h // 2, w // 2)

    # Create ramps
    ramp = torch.linspace(0, 1, radius, device=device)

    # Top edge
    mask[:radius, :] *= ramp.unsqueeze(1)
    # Bottom edge
    mask[-radius:, :] *= ramp.flip(0).unsqueeze(1)
    # Left edge
    mask[:, :radius] *= ramp.unsqueeze(0)
    # Right edge
    mask[:, -radius:] *= ramp.flip(0).unsqueeze(0)

    return mask


class StitchTiles:
    """
    Reconstructs an image from tiles using the metadata provided by CreateTiles.
    Includes automatic feathering to blend seams.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "tiles": (
                    "IMAGE",
                    {
                        "tooltip": "The batch of tiles to be stitched back together."
                    },
                ),
                "stitch_info": (
                    "STITCH_INFO",
                    {"tooltip": "Metadata generated by the CreateTiles node."},
                ),
            }
        }

    RETURN_TYPES = ("IMAGE",)
    FUNCTION = "execute"
    CATEGORY = "SuperNodes/Tiling"

    def execute(self, tiles, stitch_info):
        if tiles.shape[0] != len(stitch_info["tiles"]):
            raise ValueError(
                f"Mismatch: Info expects {len(stitch_info['tiles'])} tiles, but got {tiles.shape[0]}."
            )

        device = tiles.device

        # Detect resizing (e.g. if tiles were upscaled)
        current_tile_h, current_tile_w = tiles.shape[1], tiles.shape[2]
        orig_tile_h = stitch_info["tiles"][0]["h"]
        orig_tile_w = stitch_info["tiles"][0]["w"]

        scale_h = current_tile_h / orig_tile_h
        scale_w = current_tile_w / orig_tile_w

        final_h = round(stitch_info["original_height"] * scale_h)
        final_w = round(stitch_info["original_width"] * scale_w)
        original_batch_size = stitch_info["original_batch_size"]
        channels = tiles.shape[3]

        out_image = torch.zeros(
            (original_batch_size, final_h, final_w, channels), device=device
        )
        out_weights = torch.zeros(
            (original_batch_size, final_h, final_w, 1), device=device
        )

        # Calculate blending radius
        # We use a radius proportional to the overlap, but robust enough to cover the seams.
        # Since tiles can slightly vary in position due to scale, we use the max dimension for smooth falloff.
        effective_radius = max(current_tile_h, current_tile_w) // 4
        # Note: generate_feather_mask handles large radii gracefully by clamping to half-size internally.

        weight_mask = generate_feather_mask(
            (current_tile_h, current_tile_w), effective_radius, device
        )
        weight_mask = weight_mask.unsqueeze(-1)

        for i, tile_meta in enumerate(stitch_info["tiles"]):
            b_idx = tile_meta["b_index"]
            tile_img = tiles[i]

            # Map original coordinates to new scaled coordinates
            y_start = round(tile_meta["y"] * scale_h)
            x_start = round(tile_meta["x"] * scale_w)

            y_end = y_start + current_tile_h
            x_end = x_start + current_tile_w

            # Bounds check for rounding errors
            y_end = min(y_end, final_h)
            x_end = min(x_end, final_w)

            h_actual = y_end - y_start
            w_actual = x_end - x_start

            if h_actual <= 0 or w_actual <= 0:
                continue

            tile_crop = tile_img[:h_actual, :w_actual, :]
            mask_crop = weight_mask[:h_actual, :w_actual, :]

            out_image[b_idx, y_start:y_end, x_start:x_end, :] += (
                tile_crop * mask_crop
            )
            out_weights[b_idx, y_start:y_end, x_start:x_end, :] += mask_crop

        out_weights[out_weights == 0] = 1.0
        final_image = out_image / out_weights

        return (final_image,)


NODE_CLASS_MAPPINGS = {"SuperStitchTiles": StitchTiles}

NODE_DISPLAY_NAME_MAPPINGS = {"SuperStitchTiles": "🐧 Stitch Tiles"}
