import numpy as np
from PIL import Image
import torch


class RestoreMaskCrop:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "original_image": (
                    "IMAGE",
                    {"tooltip": "The original source image before cropping."},
                ),
                "cropped_image": (
                    "IMAGE",
                    {
                        "tooltip": "The processed cropped image to be pasted back."
                    },
                ),
                "crop_info": (
                    "CROP_INFO",
                    {
                        "tooltip": "The crop metadata generated by the ImageMaskCrop node."
                    },
                ),
                "strategy": (
                    ["scale_cropped", "scale_original"],
                    {
                        "tooltip": "How to handle size mismatches. 'scale_cropped' resizes the input crop to the original hole. 'scale_original' resizes the background to match the new crop scale."
                    },
                ),
                "scale_method": (
                    ["nearest-exact", "bilinear", "area", "bicubic", "lanczos"],
                    {
                        "tooltip": "The interpolation method used for resizing images."
                    },
                ),
            },
            "optional": {
                "cropped_mask": (
                    "MASK",
                    {
                        "tooltip": "An optional mask to use for blending, overriding the original crop mask."
                    },
                ),
            },
        }

    RETURN_TYPES = ("IMAGE",)
    OUTPUT_TOOLTIPS = (
        "The composite image with the crop restored to its original location.",
    )
    FUNCTION = "restore"
    CATEGORY = "SuperNodes/Image"
    DESCRIPTION = "Restores a cropped image back into the original image context, handling scaling and blending."

    def restore(
        self,
        original_image,
        cropped_image,
        crop_info,
        strategy,
        scale_method,
        cropped_mask=None,
    ):
        def resize_tensor(tensor, width, height, method, is_mask=False):
            """
            Optimized resizing using torch.interpolate where possible,
            falling back to PIL for Lanczos.
            """
            # Use PIL for Lanczos
            if method == "lanczos":
                return pil_resize_fallback(
                    tensor, width, height, method, is_mask
                )

            # Map method names to torch modes
            # "nearest-exact" -> "nearest"
            mode = method if method != "nearest-exact" else "nearest"

            # Images: [B, H, W, C] -> [B, C, H, W]
            # Masks:  [B, H, W]    -> [B, 1, H, W]
            if is_mask:
                if tensor.dim() == 3:
                    t = tensor.unsqueeze(1)
                else:
                    t = tensor
            else:
                t = tensor.permute(0, 3, 1, 2)

            # Perform Interpolation
            if mode in ["bilinear", "bicubic"]:
                t = torch.nn.functional.interpolate(
                    t, size=(height, width), mode=mode, align_corners=False
                )
            else:
                # area / nearest
                t = torch.nn.functional.interpolate(
                    t, size=(height, width), mode=mode
                )

            # Restore Dimensions
            if is_mask:
                # [B, 1, H, W] -> [B, H, W]
                return t.squeeze(1)
            else:
                # [B, C, H, W] -> [B, H, W, C]
                return t.permute(0, 2, 3, 1)

        def pil_resize_fallback(
            tensor_data, width, height, method, is_mask=False
        ):
            pil_method = Image.Resampling.LANCZOS
            if method == "nearest-exact":
                pil_method = Image.Resampling.NEAREST
            elif method == "area":
                pil_method = Image.Resampling.BOX
            elif method == "bicubic":
                pil_method = Image.Resampling.BICUBIC
            elif method == "bilinear":
                pil_method = Image.Resampling.BILINEAR

            results = []
            if is_mask:
                # Handle Mask [B, H, W]
                for m in tensor_data:
                    i = Image.fromarray(
                        (m.cpu().numpy() * 255.0).clip(0, 255).astype(np.uint8),
                        mode="L",
                    )
                    i = i.resize((width, height), resample=pil_method)
                    results.append(
                        torch.from_numpy(np.array(i).astype(np.float32) / 255.0)
                    )
            else:
                # Handle Image [B, H, W, C]
                for img in tensor_data:
                    i = Image.fromarray(
                        (img.cpu().numpy() * 255.0)
                        .clip(0, 255)
                        .astype(np.uint8)
                    )
                    i = i.resize((width, height), resample=pil_method)
                    results.append(
                        torch.from_numpy(np.array(i).astype(np.float32) / 255.0)
                    )

            return torch.stack(results)

        # Unpack info
        orig_x, orig_y = crop_info["x"], crop_info["y"]
        orig_w, orig_h = crop_info["w"], crop_info["h"]

        # Determine the blending mask
        if cropped_mask is not None:
            composite_mask = cropped_mask
        else:
            composite_mask = crop_info.get(
                "mask_patch",
                torch.ones((1, cropped_image.shape[1], cropped_image.shape[2])),
            )

        # Ensure mask batch size matches image
        if composite_mask.shape[0] < cropped_image.shape[0]:
            composite_mask = composite_mask.repeat(cropped_image.shape[0], 1, 1)

        if strategy == "scale_cropped":
            # Resize the cropped_image to fit the original hole
            if (cropped_image.shape[2] != orig_w) or (
                cropped_image.shape[1] != orig_h
            ):
                cropped_image = resize_tensor(
                    cropped_image, orig_w, orig_h, scale_method, is_mask=False
                )
                composite_mask = resize_tensor(
                    composite_mask, orig_w, orig_h, scale_method, is_mask=True
                )

            out_image = original_image.clone()
            paste_x, paste_y = orig_x, orig_y

        elif strategy == "scale_original":
            # Calculate scale factor based on the difference between the NEW crop width and the OLD crop width
            # This causes the original image to scale proportionally to how the crop was scaled
            scale_factor = cropped_image.shape[2] / orig_w

            # New dimensions for the full original image
            new_orig_w = int(crop_info["original_size"][1] * scale_factor)
            new_orig_h = int(crop_info["original_size"][0] * scale_factor)

            # 1. Resize the background (original) image
            out_image = resize_tensor(
                original_image,
                new_orig_w,
                new_orig_h,
                scale_method,
                is_mask=False,
            )

            # 2. Resize the blending mask to match the NEW crop size
            if (composite_mask.shape[2] != cropped_image.shape[2]) or (
                composite_mask.shape[1] != cropped_image.shape[1]
            ):
                composite_mask = resize_tensor(
                    composite_mask,
                    cropped_image.shape[2],
                    cropped_image.shape[1],
                    scale_method,
                    is_mask=True,
                )

            # 3. Calculate new paste coordinates
            paste_x = int(round(orig_x * scale_factor))
            paste_y = int(round(orig_y * scale_factor))

        # Get dimensions
        h_ins, w_ins = cropped_image.shape[1], cropped_image.shape[2]
        max_h, max_w = out_image.shape[1], out_image.shape[2]

        # Calculate valid intersection (clipping)
        # Coordinates in out_image
        y1 = max(0, paste_y)
        x1 = max(0, paste_x)
        y2 = min(max_h, paste_y + h_ins)
        x2 = min(max_w, paste_x + w_ins)

        # If the paste area is entirely out of bounds, return early
        if y2 <= y1 or x2 <= x1:
            return (out_image,)

        # Coordinates in cropped_image (source)
        # We need to offset if we clipped top/left
        sy1 = y1 - paste_y
        sx1 = x1 - paste_x
        # Width/Height of the valid region
        region_h = y2 - y1
        region_w = x2 - x1
        sy2 = sy1 + region_h
        sx2 = sx1 + region_w

        # Extract regions
        dest_region = out_image[:, y1:y2, x1:x2, :]
        src_region = cropped_image[:, sy1:sy2, sx1:sx2, :]
        mask_region = composite_mask[:, sy1:sy2, sx1:sx2]

        # Expand mask for broadcasting: [B, H, W] -> [B, H, W, 1]
        mask_region = mask_region.unsqueeze(-1)

        # Blend
        blended = src_region * mask_region + dest_region * (1.0 - mask_region)

        # Apply back to output
        out_image[:, y1:y2, x1:x2, :] = blended

        return (out_image,)


NODE_CLASS_MAPPINGS = {"RestoreMaskCrop": RestoreMaskCrop}

NODE_DISPLAY_NAME_MAPPINGS = {"RestoreMaskCrop": "🐧 Restore Mask Crop"}
