from comfy_api.latest import io
import torch

from .utils import SCALE_METHODS, scale_image, scale_mask


class RestoreMaskCrop(io.ComfyNode):
    @classmethod
    def define_schema(cls) -> io.Schema:
        return io.Schema(
            node_id="RestoreMaskCrop",
            display_name="🐧 Restore Mask Crop",
            category="SuperNodes/Image",
            description="Restores a cropped image back into the original image context, handling scaling and blending.",
            inputs=[
                io.Image.Input(
                    "original_image",
                    tooltip="The original source image before cropping.",
                ),
                io.Image.Input(
                    "cropped_image",
                    tooltip="The processed cropped image to be pasted back.",
                ),
                io.Custom("CROP_INFO").Input(
                    "crop_info",
                    tooltip="The crop metadata generated by the ImageMaskCrop node.",
                ),
                io.Combo.Input(
                    "scale",
                    options=["cropped", "original"],
                    tooltip="Which image to resize on a size mismatch. 'cropped' resizes the incoming crop to fit the original hole. 'original' resizes the background to match the new crop scale.",
                ),
                io.Combo.Input(
                    "scale_method",
                    options=SCALE_METHODS,
                    tooltip="The interpolation method used for resizing images.",
                ),
                io.Mask.Input(
                    "cropped_mask",
                    optional=True,
                    tooltip="An optional mask to use for blending, overriding the original crop mask.",
                ),
            ],
            outputs=[
                io.Image.Output(
                    tooltip="The composite image with the crop restored to its original location."
                ),
            ],
        )

    @classmethod
    def execute(
        cls,
        original_image,
        cropped_image,
        crop_info,
        scale,
        scale_method,
        cropped_mask=None,
    ) -> io.NodeOutput:
        # Unpack info
        orig_x, orig_y = crop_info["x"], crop_info["y"]
        orig_w, orig_h = crop_info["w"], crop_info["h"]

        # Determine the blending mask
        if cropped_mask is not None:
            composite_mask = cropped_mask
        else:
            composite_mask = crop_info.get(
                "mask_patch",
                torch.ones((1, cropped_image.shape[1], cropped_image.shape[2])),
            )

        # Ensure mask batch size matches image
        if composite_mask.shape[0] < cropped_image.shape[0]:
            composite_mask = composite_mask.repeat(cropped_image.shape[0], 1, 1)

        if scale == "cropped":
            # Resize the cropped_image to fit the original hole
            if (cropped_image.shape[2] != orig_w) or (
                cropped_image.shape[1] != orig_h
            ):
                cropped_image = scale_image(
                    cropped_image, orig_w, orig_h, scale_method
                )
                composite_mask = scale_mask(
                    composite_mask, orig_w, orig_h, scale_method
                )

            out_image = original_image.clone()
            paste_x, paste_y = orig_x, orig_y

        elif scale == "original":
            # Calculate scale factor based on the difference between the NEW crop width and the OLD crop width
            # This causes the original image to scale proportionally to how the crop was scaled
            scale_factor = cropped_image.shape[2] / orig_w

            # New dimensions for the full original image
            new_orig_w = int(crop_info["original_size"][1] * scale_factor)
            new_orig_h = int(crop_info["original_size"][0] * scale_factor)

            # 1. Resize the background (original) image
            out_image = scale_image(
                original_image, new_orig_w, new_orig_h, scale_method
            )

            # 2. Resize the blending mask to match the NEW crop size
            if (composite_mask.shape[2] != cropped_image.shape[2]) or (
                composite_mask.shape[1] != cropped_image.shape[1]
            ):
                composite_mask = scale_mask(
                    composite_mask,
                    cropped_image.shape[2],
                    cropped_image.shape[1],
                    scale_method,
                )

            # 3. Calculate new paste coordinates
            paste_x = int(round(orig_x * scale_factor))
            paste_y = int(round(orig_y * scale_factor))

        # Get dimensions
        h_ins, w_ins = cropped_image.shape[1], cropped_image.shape[2]
        max_h, max_w = out_image.shape[1], out_image.shape[2]

        # Calculate valid intersection (clipping)
        # Coordinates in out_image
        y1 = max(0, paste_y)
        x1 = max(0, paste_x)
        y2 = min(max_h, paste_y + h_ins)
        x2 = min(max_w, paste_x + w_ins)

        # If the paste area is entirely out of bounds, return early
        if y2 <= y1 or x2 <= x1:
            return io.NodeOutput(out_image)

        # Coordinates in cropped_image (source)
        # We need to offset if we clipped top/left
        sy1 = y1 - paste_y
        sx1 = x1 - paste_x
        # Width/Height of the valid region
        region_h = y2 - y1
        region_w = x2 - x1
        sy2 = sy1 + region_h
        sx2 = sx1 + region_w

        # Extract regions
        dest_region = out_image[:, y1:y2, x1:x2, :]
        src_region = cropped_image[:, sy1:sy2, sx1:sx2, :]
        mask_region = composite_mask[:, sy1:sy2, sx1:sx2]

        # Expand mask for broadcasting: [B, H, W] -> [B, H, W, 1]
        mask_region = mask_region.unsqueeze(-1)

        # Blend
        blended = src_region * mask_region + dest_region * (1.0 - mask_region)

        # Apply back to output
        out_image[:, y1:y2, x1:x2, :] = blended

        return io.NodeOutput(out_image)


NODE = [RestoreMaskCrop]
